### ISSUE TITLE
Expose Usage Limit Headers as part of responses

### ISSUE THREAD

**Issue by andrewmunn** [peopledatalabs/peopledatalabs-js#210]
**Is your feature request related to a problem? Please describe.**
I want to implement a metric to monitor our usage of PDL and ensure we do not run out of usage credits. Your API requests [return your remaining credits as response headers](https://docs.peopledatalabs.com/docs/usage-limits). However, as far as I can tell, there is no way to access the response headers when using this JS client.

**Describe the solution you'd like**
I'd like the usage headers to be exposed as part of the response.

**Describe alternatives you've considered**
I'm considering not using this client (or copying it) and implementing the API myself to get around this.

**Comment by vvillait88** [comment]
@andrewmunn We actually parse and return the rate limit information as part of the response object under the `rateLimit` key.  Here are the associated types for reference:

```
export interface RateLimit {
  rateLimitRemaining?: RateLimitRemaining;
  rateLimitReset?: string;
  rateLimitLimit?: RateLimitLimit;
  totalLimitOveragesRemaining?: number;
  totalLimitPurchasedRemaining?: number;
  totalLimitRemaining?: number;
  callCreditsType?: string;
  callCreditsSpent?: number;
  lifetimeUsed?: number;
}

export interface RateLimitRemaining {
  minute?: number;
  day?: number;
  month?: number;
}

export interface RateLimitLimit {
  minute?: number;
  day?: number;
  month?: number;
}
```
