### ISSUE TITLE
Use `POST` with` JSON` schema for search parameters instead of plain `SQL` in `JavaScript`?

### ISSUE THREAD

**Issue by alamenai** [peopledatalabs/peopledatalabs-js#238]
**Is your feature request related to a problem? Please describe.**

As a frontend developer who relies on TypeScript and Zod schemas, I struggle with SQL schema and how they work though I have knowledge about SQL and relational databases, but I see that writing SQL in code is not the appropriate way to call APIs.

**Describe the solution you'd like**
The solution I would suggest is the same as used by core signal API by tell the user the Schema of the search and sending as POST request with a body as JSON.

**Comment by vvillait88** [comment]
@alamenai Thanks for opening your request.  We currently do not support parameterized search in our APIs, only ESQuery or SQL.  If you would like this feature, I would encourage you to open a feature request here: https://feedback.peopledatalabs.com/.  If our API team decides to move forward with your request, we can support that via our SDK.

**Comment by alamenai** [comment]
Thank you @vvillait88 , I'll forward the request.
