### ISSUE TITLE
cannot instantiate PDL with new keyword throws ERROR [ExceptionHandler] peopledatalabs_1.default is not a constructor

### ISSUE THREAD

**Issue by faithfulojebiyi** [peopledatalabs/peopledatalabs-js#243]
**Describe the bug**

**To Reproduce**
import it into a nestjs code base without esModuleInterop set to true
<img width="1146" alt="Screenshot 2024-07-24 at 10 55 50" src="https://github.com/user-attachments/assets/2fb1b6d0-df25-47c2-980e-5e243dc945b8">

**Expected behavior**
should work out of the box
i tried import * as ... still did not work

**Screenshots**
<img width="511" alt="Screenshot 2024-07-24 at 10 53 46" src="https://github.com/user-attachments/assets/dd68ea93-1b62-4b31-8402-ef00abe62c7f">

 - peopledatalabs Library Version 9.0.0
 - Node Version 20
 - PNPM Version 8.15.7

**Additional context**
i dont wan to  set esModuleInterop  to true this will mess up other imports. 
I believe this is relate to how this package is bundled.

**Comment by faithfulojebiyi** [comment]
Any updates on this

**Comment by vvillait88** [comment]
@faithfulojebiyi Thanks for opening the issue.  We are looking into it and should have a followup next week if we can accommodate this request.

**Comment by vvillait88** [comment]
@faithfulojebiyi After investigation, we will not be supporting esModuleInterop turned off.  We looked into other libraries and saw this was pretty common practice.  If your project needs this setting turned off, we suggest either hitting the APIs directly or forking this library and making the adjustments you need.
