### ISSUE TITLE
Issue with 3.1.3

### ISSUE THREAD

**Issue by enricoros** [peopledatalabs/peopledatalabs-js#29]
**Describe the bug**
Upgrading to 3.1.3, from 3.1.2 breaks the app.
The error surfaces at runtime, and I'm unsure on whether it's coming from the server-side (next.js pages/api) or the module, or some mismatch of module format compatibility. I can only see on the console the following message, without traces:
`error - ReferenceError: self is not defined`

**To Reproduce**
Not easy, the module is used in a complex Next.js application. It's imported as follows:
```
  import PDLJS from 'peopledatalabs';
  ...
  private PDLJSClient = new PDLJS({ 'apiKey': ... });
```

**Expected behavior**
The application shall run; instead a red error message about missing 'self' shows up.

**Screenshots**
Update: attached code that causes the 'self'.. issue.
 - peopledatalabs 3.1.3
 - Node Version 16.13.2
 - NPM Version 7.11.2

**Additional context**
Update:
Seems to be something related to migrating from CJS modules (3.1.2) to UMD (3.1.3).
In particular the following line in `main.umd.js` seems to cause the problem:
`(e || self).peopledatalabs`

![image](https://user-images.githubusercontent.com/32999/175766974-ef4aed13-6bd4-4f62-aaff-f62902072a37.png)

![image](https://user-images.githubusercontent.com/32999/175767006-721a2f19-5b31-4b3f-bd02-ff447ef20853.png)

**Comment by vvillait88** [comment]
@enricoros Thanks for bringing this to our attention, we have unpublished v3.1.3 and rolled it back to v3.1.2 until we trace the issue here.  Please update your package.json to use "peopledatalabs": "^3.1.2"

**Comment by vvillait88** [comment]
@enricoros We pushed an update yesterday that should resolve issues with the library around typescript compiling as well as our new headers.
