### ISSUE TITLE
PersonResponse type doesn't seem to match PDL API response

### ISSUE THREAD

**Issue by mpalmerlee** [peopledatalabs/peopledatalabs-js#39]
**Describe the bug**
There are a couple of properties on the `PersonResponse` type (and sub-types) defined as strings that the API seems to return as different types. Specifically `job_company_founded` (is a Number from the API data I've seen), PersonExperienceResponse `company.founded` should also be a number, and `is_primary` should be a boolean value.

**To Reproduce**
`curl "https://api.peopledatalabs.com/v5/person/enrich?api_key=${API_KEY}&pretty=True&profile=linkedin.com/in/seanthorne"`
Then take the data part of the output and declare a var in TypeScript:
```
export const fullPdlResponse: PersonResponse = {
...
}
```
Notice the type errors for the properties above.

**Expected behavior**
The output from the API should match the type definition.

**Screenshots**
<img width="941" alt="Screen Shot 2022-08-17 at 10 40 46 AM" src="https://user-images.githubusercontent.com/515850/185206426-7121988b-db59-4d53-b964-044a6bf3dd0b.png">

 - peopledatalabs Library Version 4.0.2
 - Node Version 16.15.0
 - NPM Version 8.5.5

**Additional context**

**Comment by vvillait88** [comment]
@mpalmerlee fixed in PR https://github.com/peopledatalabs/peopledatalabs-js/pull/40

**Comment by mpalmerlee** [comment]
Thank you for the quick response and turn-around @vvillait88 I just installed version 4.0.3 of the library and it seems that the fix didn't come through. Perhaps there is a build / compile step that didn't happen to publish that type?

**Comment by mpalmerlee** [comment]
@vvillait88 sorry correction, that fixed those issues, I do see an extra property now that's giving me an error that isn't defined on the: `last_initial` this isn't as big deal for me though since I'm not going to use that one.
