### ISSUE TITLE
Type definitions are not been exported

### ISSUE THREAD

**Issue by assapir** [peopledatalabs/peopledatalabs-js#43]
**Describe the bug**
When trying to use the SDK with TypeScript, I expect that types of response will be inferred, but this not actually happens, nor the inner types (like `PersonEnrichmentResponse` for example) can't be imported because they are not exported from `index.d.ts`

**To Reproduce**
Try to use a type from the library that is not directly under the `PDLJS` class declaration.

**Expected behavior**
I can import types and types are inferred in the correct way.

**Screenshots**
1: this is the right type: 
![image](https://user-images.githubusercontent.com/4030466/210513725-18cc4026-a2a0-4007-915c-60671333083d.png)
2: but it doesn't go to the internal type:
![image](https://user-images.githubusercontent.com/4030466/210513788-3810b337-f15b-4a50-a0bd-298cd023e687.png)
3: nor it can be imported:
![image](https://user-images.githubusercontent.com/4030466/210513890-21937716-8ccc-4bf9-9fc1-d152191dfd86.png)

 - peopledatalabs Library Version: `4.0.3`
 - Node Version: `19.3.0`
 - NPM Version

**Additional context**

**Comment by vvillait88** [comment]
@assapir I was able to import PersonEnrichmentResponse from using `import { PersonEnrichmentResponse } from 'peopledatalabs/dist/types/enrichment-types';` in some example code together.  Can you confirm that this doesn't work for you?

**Comment by assapir** [comment]
importing directly from types does work. I do, how ever, suggest to re-export it from the main index

**Comment by vvillait88** [comment]
@assapir I have opened https://github.com/peopledatalabs/peopledatalabs-js/pull/45 to address this

**Comment by assapir** [comment]
Thanks 🙏
