### ISSUE TITLE
titlecase in bulk retrieve people function

### ISSUE THREAD

**Issue by ded-ditat** [peopledatalabs/peopledatalabs-js#51]
**Is your feature request related to a problem? Please describe.**
It doesn't look like we can pass titlecase: true when using the bulk person retrieve function. It looks like the api supports this could it be added as a param?

**Describe the solution you'd like**
Have titlecase as a param we can use in the bulk person retrieve function.

**Describe alternatives you've considered**
If theres a good work around we're open.

**Additional context**
We are using search preview in our front end and then use bulk retrieve calls with the pdl ids from the initial search. We have titlecase: true on the search params then end up returning lowercase everything with the retrieve function. We're enterprise customers as well.

**Comment by vvillait88** [comment]
@ded-ditat i've opened a PR to support this.  As soon as it's merged, you can pass in the params as an object.  For example, PDLJSClient.person.bulk.enrichment(bulkEnrichmentRecords, { titlecase: true})
